"""Contrato de presentación y traducciones de Excel."""
XLSX_MAX_ACTIVITY_SERIES_SAMPLES = 25_000


XLSX_PRESENTATION_VERSION = "1.0.0"


XLSX_TRANSLATIONS = {
    "sport": {
        "running": "Carrera",
        "trail_running": "Carrera por montaña",
        "trail running": "Carrera por montaña",
        "treadmill_running": "Carrera en cinta",
        "road_biking": "Ciclismo en carretera",
        "cycling": "Ciclismo",
        "indoor_cardio": "Cardio en interior",
        "strength_training": "Fuerza",
        "strength": "Fuerza",
        "walking": "Caminar",
        "walking_indoor": "Caminar en interior",
        "assistance": "Otro",
        "other": "Otro",
    },
    "time_bucket": {
        "morning": "Mañana",
        "afternoon": "Tarde",
        "evening": "Noche",
        "night": "Madrugada",
    },
    "session_type": {
        "interval": "Intervalos",
        "easy": "Rodaje fácil",
        "long_run": "Tirada larga",
        "cross_training": "Entrenamiento cruzado",
        "strength": "Fuerza",
        "tempo": "Tempo",
        "threshold": "Umbral",
        "race": "Competición",
        "recovery": "Recuperación",
        "unknown": "Sin clasificar",
        "uncategorized": "Sin clasificar",
    },
    "training_benefit": {
        "UNKNOWN": "Desconocido",
        "RECOVERY": "Recuperación",
        "AEROBIC_BASE": "Base aeróbica",
        "TEMPO": "Tempo",
        "LACTATE_THRESHOLD": "Umbral de lactato",
        "VO2MAX": "VO₂ máx.",
        "ANAEROBIC_BASE": "Base anaeróbica",
        "SPEED": "Velocidad",
    },
    "week_status": {
        "complete": "Completa",
        "partial_start": "Parcial al inicio",
        "partial_end": "Parcial al final",
        "partial_both": "Parcial",
        "current": "En curso",
        "empty": "Sin entrenamientos",
    },
    "lap_type": {
        "WARMUP": "Calentamiento",
        "ACTIVE": "Activa",
        "INTERVAL_ACTIVE": "Activa",
        "REST": "Recuperación",
        "COOLDOWN": "Enfriamiento",
        "RECOVERY": "Recuperación",
    },
    "zone_type": {
        "heart_rate": "Frecuencia cardiaca",
        "power": "Potencia",
        "below_zone_1": "Por debajo de zona 1",
    },
    "gear_type": {
        "Shoes": "Zapatillas",
        "shoes": "Zapatillas",
        "Bike": "Bicicleta",
        "bike": "Bicicleta",
    },
    "gear_status": {
        "active": "Activo",
        "retired": "Retirado",
        "ACTIVE": "Activo",
        "RETIRED": "Retirado",
    },
    "feeling": {
        "very_weak": "Muy flojo",
        "weak": "Flojo",
        "strong": "Fuerte",
        "normal": "Normal",
        "good": "Bien",
        "very_good": "Muy bien",
        "POOR": "Mala",
        "FAIR": "Regular",
        "GOOD": "Buena",
        "EXCELLENT": "Excelente",
    },
    "sleep": {
        "POOR": "Mala",
        "FAIR": "Regular",
        "GOOD": "Buena",
        "EXCELLENT": "Excelente",
    },
    "hrv": {
        "BALANCED": "Equilibrada",
        "UNBALANCED": "Desequilibrada",
        "LOW": "Baja",
        "POOR": "Baja",
        "GOOD": "Buena",
    },
    "readiness": {
        "POOR": "Baja",
        "LOW": "Baja",
        "MODERATE": "Moderada",
        "HIGH": "Alta",
        "PRIME": "Óptima",
    },
    "habit": {
        "illness": "Enfermedad",
        "injury": "Molestia o lesión",
        "travel": "Viaje",
        "alcohol": "Alcohol",
        "caffeine": "Cafeína",
        "nap": "Siesta",
    },
    "privacy": {
        "redact_personal_identifiers": "Identidad oculta automáticamente",
        "automatic": "Automática",
    },
    "interval_type": {
        "RWD_RUN": "Carrera/caminar",
        "RWD_WALK": "Caminar",
        "RWD_STAND": "Parado",
        "RUN": "Carrera",
        "WARMUP": "Calentamiento",
        "ACTIVE": "Activo",
        "INTERVAL_ACTIVE": "Activo",
        "INTERVAL": "Intervalo",
        "INTERVAL_REST": "Recuperación",
        "INTERVAL_RECOVERY": "Recuperación",
        "INTERVAL_WARMUP": "Calentamiento",
        "INTERVAL_COOLDOWN": "Enfriamiento",
        "REST": "Recuperación",
        "COOLDOWN": "Enfriamiento",
        "RECOVERY": "Recuperación",
    },
}


XLSX_QUALITY_NAMES = {
    "sleep_duration_s": "Duración del sueño",
    "sleep_score": "Puntuación del sueño",
    "hrv_overnight_ms": "VFC nocturna",
    "resting_heart_rate_bpm": "Frecuencia cardiaca en reposo",
    "average_stress": "Estrés medio",
    "body_battery_high": "Body Battery máximo",
    "self_evaluation": "Autoevaluación de actividades válidas",
    "garmin_training_load": "Carga Garmin",
}
